# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

workspace 'QuickReleaseNotesDemo.xcworkspace'
project 'QuickReleaseNotesDemo.xcodeproj'

target 'QuickReleaseNotesDemo' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for QuickReleaseNotesDemo
  pod 'QuickReleaseNotes'
end
